language: node_js
node_js:
  - 11.6.0

cache: npm

install:
  - npm install
  
script:

  - docker pull mateunix/bdd-test
  - docker run -it -v $PWD:/e2e -w /e2e cypress/included
  - docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://agredevops.netlify.app/

after_success:
  - bash ./telegram_notification.sh
  