language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install
  
script:
  - docker pull mateunix/bdd-test
  - docker run -it -v $PWD:/e2e -w /e2e cypress/included
  

after_success:
  - bash ./telegram_notification.sh
  