os: linux
dist: focal
language: node_js
node_js:
      - 18
cache: npm
jobs:
  include:
    - stage: build
      script:   
        - npm install

    - stage: test
      script:
        - npm start &
    #Execucao do cypress no nosso site hosteado
        - docker run -it -v -p 3000:3000 $PWD:/e2e -w /e2e cypress/included
        - echo "Teste bdd concluido"
    #Execucao do OWASP ZAP no nosso site hosteado, ignorando warnings (apenas parando se houver algum problema)
      #- docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://agredevops.netlify.app/ 2> /dev/null; (($? == 2)) && echo 'Done' >&2 
      #- echo "Teste zap concluido"

    - stage: deploy
      before_deploy:
        - npm install netlify-cli -g
        - yarn build
      deploy:
        provider: script
        edge: true
        script: netlify deploy --dir=build --prod
        on:
          branch: main
      after_deploy:
        # Em caso de sucesso enviará uma mensagem para o telegram
        - bash ./telegram_notification.sh
        - echo "Success! :D"