language: node_js

os: linux

dist: focal

node_js:
  - 18.18.0

cache: npm

install:
  - npm install
  
script:

  - docker pull mateunix/bdd-test:5.0
  - docker run mateunix/bdd-test:5.0
  #- docker run -it -v $PWD:/e2e -w /e2e cypress/included
  - docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://agredevops.netlify.app/ 2> /dev/null; (($? == 2)) && echo 'Done' >&2 

after_success:
  - bash ./telegram_notification.sh
  